discussions_create:
    path: /discussions/create
    methods: GET|POST
    controller: App\UserInterface\Controller\CreateDiscussionController
discussions_paginate:
    path: /discussions/list
    methods: GET
    controller: App\UserInterface\Controller\PaginateDiscussionController
discussions_show:
    path: /discussions/{discussionId}
    methods: GET|POST
    controller: App\UserInterface\Controller\ShowDiscussionController
profile:
    path: /profile
    methods: GET
    controller: App\UserInterface\Controller\ProfileController
index:
    path: /
    methods: GET
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults: 
        template: index.html.twig
        context:
            keycloakHome: '%app.keycloak_home%'
logout:
    path: /logout
openid_redirecturi:
    path: /redirect-uri
