registration:
    path: /registration
    methods: GET|POST
    controller: App\UserInterface\Controller\RegistrationController
create_discussion:
    path: /create-discussion
    methods: GET|POST
    controller: App\UserInterface\Controller\CreateDiscussionController
login:
    path: /login
    methods: GET|POST
    controller: App\UserInterface\Controller\LoginController
index:
    path: /
    methods: GET
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults: 
        template: index.html.twig
